# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ml_remaining', models.PositiveIntegerField(verbose_name=b'Remaining (ml)')),
            ],
        ),
        migrations.CreateModel(
            name='FlavourInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavour_instances', to='vaper.Flavour')),
            ],
            options={
                'verbose_name_plural': 'Flavours',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='flavourinstance',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavour_instances', to='vaper.Recipe'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavours', to='vaper.Manufacturer'),
        ),
        migrations.AlterUniqueTogether(
            name='flavour',
            unique_together=set([('name', 'manufacturer')]),
        ),
    ]
