# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='ml_remaining',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flavourinstance',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavour_instances', to='vaper.Flavour'),
        ),
        migrations.AlterField(
            model_name='flavourinstance',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavour_instances', to='vaper.Recipe'),
        ),
    ]
