# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaper', '0002_flavour_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='ml_remaining',
        ),
    ]
