# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaper', '0002_auto_20160603_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='ml_remaining',
            field=models.PositiveIntegerField(verbose_name=b'Remaining (ml)'),
        ),
    ]
